// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package services

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const ROLE_ADMIN = "admin"
const ROLE_SUPERADMIN = "superadmin"
const SERVICE_SPORTACTIVITY = "Activity"
const SERVICE_USER = "User"
const SERVICE_IMAGE = "Image"
const SERVICE_SPORT = "Sport"
const SERVICE_CITY = "City"
const SERVICE_AREA = "Area"

func init() {
}
