// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package services

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var GoUnusedProtection__ int

// Attributes:
//  - What
//  - Why
type InvalidOperation struct {
	What int32  `thrift:"what,1" db:"what" json:"what"`
	Why  string `thrift:"why,2" db:"why" json:"why"`
}

func NewInvalidOperation() *InvalidOperation {
	return &InvalidOperation{}
}

func (p *InvalidOperation) GetWhat() int32 {
	return p.What
}

func (p *InvalidOperation) GetWhy() string {
	return p.Why
}
func (p *InvalidOperation) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *InvalidOperation) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.What = v
	}
	return nil
}

func (p *InvalidOperation) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Why = v
	}
	return nil
}

func (p *InvalidOperation) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("InvalidOperation"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *InvalidOperation) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("what", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:what: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.What)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.what (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:what: ", p), err)
	}
	return err
}

func (p *InvalidOperation) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("why", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:why: ", p), err)
	}
	if err := oprot.WriteString(string(p.Why)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.why (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:why: ", p), err)
	}
	return err
}

func (p *InvalidOperation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InvalidOperation(%+v)", *p)
}

func (p *InvalidOperation) Error() string {
	return p.String()
}

// Attributes:
//  - Message
type InvalidToken struct {
	Message string `thrift:"message,1" db:"message" json:"message"`
}

func NewInvalidToken() *InvalidToken {
	return &InvalidToken{}
}

func (p *InvalidToken) GetMessage() string {
	return p.Message
}
func (p *InvalidToken) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *InvalidToken) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Message = v
	}
	return nil
}

func (p *InvalidToken) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("InvalidToken"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *InvalidToken) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("message", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:message: ", p), err)
	}
	if err := oprot.WriteString(string(p.Message)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.message (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:message: ", p), err)
	}
	return err
}

func (p *InvalidToken) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InvalidToken(%+v)", *p)
}

func (p *InvalidToken) Error() string {
	return p.String()
}

// Attributes:
//  - Identifier
//  - Passwordhash
type UserCredentials struct {
	Identifier   string  `thrift:"identifier,1,required" db:"identifier" json:"identifier"`
	Passwordhash *string `thrift:"passwordhash,2" db:"passwordhash" json:"passwordhash,omitempty"`
}

func NewUserCredentials() *UserCredentials {
	return &UserCredentials{}
}

func (p *UserCredentials) GetIdentifier() string {
	return p.Identifier
}

var UserCredentials_Passwordhash_DEFAULT string

func (p *UserCredentials) GetPasswordhash() string {
	if !p.IsSetPasswordhash() {
		return UserCredentials_Passwordhash_DEFAULT
	}
	return *p.Passwordhash
}
func (p *UserCredentials) IsSetPasswordhash() bool {
	return p.Passwordhash != nil
}

func (p *UserCredentials) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetIdentifier bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
			issetIdentifier = true
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetIdentifier {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Identifier is not set"))
	}
	return nil
}

func (p *UserCredentials) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Identifier = v
	}
	return nil
}

func (p *UserCredentials) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Passwordhash = &v
	}
	return nil
}

func (p *UserCredentials) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UserCredentials"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserCredentials) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("identifier", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:identifier: ", p), err)
	}
	if err := oprot.WriteString(string(p.Identifier)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.identifier (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:identifier: ", p), err)
	}
	return err
}

func (p *UserCredentials) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetPasswordhash() {
		if err := oprot.WriteFieldBegin("passwordhash", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:passwordhash: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Passwordhash)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.passwordhash (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:passwordhash: ", p), err)
		}
	}
	return err
}

func (p *UserCredentials) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserCredentials(%+v)", *p)
}

// Attributes:
//  - Identifier
//  - Username
//  - Profilepicture
//  - CityID
type Profile struct {
	Identifier     *string `thrift:"identifier,1" bson:"identifier,omitempty"`
	Username       *string `thrift:"username,2" bson:"username,omitempty"`
	Profilepicture []byte  `thrift:"profilepicture,3" bson:"image_id,omitempty"`
	CityID         *string `thrift:"city_id,4" bson:"city_id,omitempty"`
}

func NewProfile() *Profile {
	return &Profile{}
}

var Profile_Identifier_DEFAULT string

func (p *Profile) GetIdentifier() string {
	if !p.IsSetIdentifier() {
		return Profile_Identifier_DEFAULT
	}
	return *p.Identifier
}

var Profile_Username_DEFAULT string

func (p *Profile) GetUsername() string {
	if !p.IsSetUsername() {
		return Profile_Username_DEFAULT
	}
	return *p.Username
}

var Profile_Profilepicture_DEFAULT []byte

func (p *Profile) GetProfilepicture() []byte {
	return p.Profilepicture
}

var Profile_CityID_DEFAULT string

func (p *Profile) GetCityID() string {
	if !p.IsSetCityID() {
		return Profile_CityID_DEFAULT
	}
	return *p.CityID
}
func (p *Profile) IsSetIdentifier() bool {
	return p.Identifier != nil
}

func (p *Profile) IsSetUsername() bool {
	return p.Username != nil
}

func (p *Profile) IsSetProfilepicture() bool {
	return p.Profilepicture != nil
}

func (p *Profile) IsSetCityID() bool {
	return p.CityID != nil
}

func (p *Profile) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Profile) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Identifier = &v
	}
	return nil
}

func (p *Profile) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Username = &v
	}
	return nil
}

func (p *Profile) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Profilepicture = v
	}
	return nil
}

func (p *Profile) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.CityID = &v
	}
	return nil
}

func (p *Profile) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Profile"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Profile) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIdentifier() {
		if err := oprot.WriteFieldBegin("identifier", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:identifier: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Identifier)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.identifier (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:identifier: ", p), err)
		}
	}
	return err
}

func (p *Profile) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetUsername() {
		if err := oprot.WriteFieldBegin("username", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:username: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Username)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.username (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:username: ", p), err)
		}
	}
	return err
}

func (p *Profile) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetProfilepicture() {
		if err := oprot.WriteFieldBegin("profilepicture", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:profilepicture: ", p), err)
		}
		if err := oprot.WriteBinary(p.Profilepicture); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.profilepicture (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:profilepicture: ", p), err)
		}
	}
	return err
}

func (p *Profile) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCityID() {
		if err := oprot.WriteFieldBegin("city_id", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:city_id: ", p), err)
		}
		if err := oprot.WriteString(string(*p.CityID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.city_id (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:city_id: ", p), err)
		}
	}
	return err
}

func (p *Profile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Profile(%+v)", *p)
}

// Attributes:
//  - Token
//  - Validity
type Token struct {
	Token    string `thrift:"token,1,required" bson:"token,omitempty"`
	Validity int64  `thrift:"validity,2,required" bson:"validity,omitempty"`
}

func NewToken() *Token {
	return &Token{}
}

func (p *Token) GetToken() string {
	return p.Token
}

func (p *Token) GetValidity() int64 {
	return p.Validity
}
func (p *Token) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetToken bool = false
	var issetValidity bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
			issetToken = true
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
			issetValidity = true
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetToken {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Token is not set"))
	}
	if !issetValidity {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Validity is not set"))
	}
	return nil
}

func (p *Token) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Token = v
	}
	return nil
}

func (p *Token) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Validity = v
	}
	return nil
}

func (p *Token) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Token"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Token) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("token", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:token: ", p), err)
	}
	if err := oprot.WriteString(string(p.Token)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.token (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:token: ", p), err)
	}
	return err
}

func (p *Token) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("validity", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:validity: ", p), err)
	}
	if err := oprot.WriteI64(int64(p.Validity)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.validity (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:validity: ", p), err)
	}
	return err
}

func (p *Token) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Token(%+v)", *p)
}

// Attributes:
//  - Identifier
//  - Password
//  - Role
//  - Profile
//  - Token
//  - Friends
//  - Friendrequests
//  - Areasvisits
//  - AnnouncedActivities
type User struct {
	Identifier          *string          `thrift:"identifier,1" bson:"username,omitempty"`
	Password            *string          `thrift:"password,2" bson:"password,omitempty"`
	Role                *string          `thrift:"role,3" bson:"role,omitempty"`
	Profile             *Profile         `thrift:"profile,4" bson:"profile,omitempty"`
	Token               *Token           `thrift:"token,5" bson:"token,omitempty"`
	Friends             []string         `thrift:"friends,6" bson:"friends,omitempty"`
	Friendrequests      []string         `thrift:"friendrequests,7" bson:"friendrequests,omitempty"`
	Areasvisits         map[int64]string `thrift:"areasvisits,8" bson:"areasvisits,omitempty"`
	AnnouncedActivities []string         `thrift:"announced_activities,9" bson:"announced_activities,omitempty"`
}

func NewUser() *User {
	return &User{}
}

var User_Identifier_DEFAULT string

func (p *User) GetIdentifier() string {
	if !p.IsSetIdentifier() {
		return User_Identifier_DEFAULT
	}
	return *p.Identifier
}

var User_Password_DEFAULT string

func (p *User) GetPassword() string {
	if !p.IsSetPassword() {
		return User_Password_DEFAULT
	}
	return *p.Password
}

var User_Role_DEFAULT string

func (p *User) GetRole() string {
	if !p.IsSetRole() {
		return User_Role_DEFAULT
	}
	return *p.Role
}

var User_Profile_DEFAULT *Profile

func (p *User) GetProfile() *Profile {
	if !p.IsSetProfile() {
		return User_Profile_DEFAULT
	}
	return p.Profile
}

var User_Token_DEFAULT *Token

func (p *User) GetToken() *Token {
	if !p.IsSetToken() {
		return User_Token_DEFAULT
	}
	return p.Token
}

var User_Friends_DEFAULT []string

func (p *User) GetFriends() []string {
	return p.Friends
}

var User_Friendrequests_DEFAULT []string

func (p *User) GetFriendrequests() []string {
	return p.Friendrequests
}

var User_Areasvisits_DEFAULT map[int64]string

func (p *User) GetAreasvisits() map[int64]string {
	return p.Areasvisits
}

var User_AnnouncedActivities_DEFAULT []string

func (p *User) GetAnnouncedActivities() []string {
	return p.AnnouncedActivities
}
func (p *User) IsSetIdentifier() bool {
	return p.Identifier != nil
}

func (p *User) IsSetPassword() bool {
	return p.Password != nil
}

func (p *User) IsSetRole() bool {
	return p.Role != nil
}

func (p *User) IsSetProfile() bool {
	return p.Profile != nil
}

func (p *User) IsSetToken() bool {
	return p.Token != nil
}

func (p *User) IsSetFriends() bool {
	return p.Friends != nil
}

func (p *User) IsSetFriendrequests() bool {
	return p.Friendrequests != nil
}

func (p *User) IsSetAreasvisits() bool {
	return p.Areasvisits != nil
}

func (p *User) IsSetAnnouncedActivities() bool {
	return p.AnnouncedActivities != nil
}

func (p *User) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		case 9:
			if err := p.ReadField9(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *User) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Identifier = &v
	}
	return nil
}

func (p *User) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Password = &v
	}
	return nil
}

func (p *User) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Role = &v
	}
	return nil
}

func (p *User) ReadField4(iprot thrift.TProtocol) error {
	p.Profile = &Profile{}
	if err := p.Profile.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Profile), err)
	}
	return nil
}

func (p *User) ReadField5(iprot thrift.TProtocol) error {
	p.Token = &Token{}
	if err := p.Token.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Token), err)
	}
	return nil
}

func (p *User) ReadField6(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Friends = tSlice
	for i := 0; i < size; i++ {
		var _elem0 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem0 = v
		}
		p.Friends = append(p.Friends, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *User) ReadField7(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Friendrequests = tSlice
	for i := 0; i < size; i++ {
		var _elem1 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem1 = v
		}
		p.Friendrequests = append(p.Friendrequests, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *User) ReadField8(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[int64]string, size)
	p.Areasvisits = tMap
	for i := 0; i < size; i++ {
		var _key2 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key2 = v
		}
		var _val3 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val3 = v
		}
		p.Areasvisits[_key2] = _val3
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *User) ReadField9(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.AnnouncedActivities = tSlice
	for i := 0; i < size; i++ {
		var _elem4 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem4 = v
		}
		p.AnnouncedActivities = append(p.AnnouncedActivities, _elem4)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *User) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("User"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := p.writeField9(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *User) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIdentifier() {
		if err := oprot.WriteFieldBegin("identifier", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:identifier: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Identifier)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.identifier (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:identifier: ", p), err)
		}
	}
	return err
}

func (p *User) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetPassword() {
		if err := oprot.WriteFieldBegin("password", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:password: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Password)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.password (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:password: ", p), err)
		}
	}
	return err
}

func (p *User) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetRole() {
		if err := oprot.WriteFieldBegin("role", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:role: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Role)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.role (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:role: ", p), err)
		}
	}
	return err
}

func (p *User) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetProfile() {
		if err := oprot.WriteFieldBegin("profile", thrift.STRUCT, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:profile: ", p), err)
		}
		if err := p.Profile.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Profile), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:profile: ", p), err)
		}
	}
	return err
}

func (p *User) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetToken() {
		if err := oprot.WriteFieldBegin("token", thrift.STRUCT, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:token: ", p), err)
		}
		if err := p.Token.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Token), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:token: ", p), err)
		}
	}
	return err
}

func (p *User) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetFriends() {
		if err := oprot.WriteFieldBegin("friends", thrift.LIST, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:friends: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Friends)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Friends {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:friends: ", p), err)
		}
	}
	return err
}

func (p *User) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetFriendrequests() {
		if err := oprot.WriteFieldBegin("friendrequests", thrift.LIST, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:friendrequests: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Friendrequests)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Friendrequests {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:friendrequests: ", p), err)
		}
	}
	return err
}

func (p *User) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetAreasvisits() {
		if err := oprot.WriteFieldBegin("areasvisits", thrift.MAP, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:areasvisits: ", p), err)
		}
		if err := oprot.WriteMapBegin(thrift.I64, thrift.STRING, len(p.Areasvisits)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range p.Areasvisits {
			if err := oprot.WriteI64(int64(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:areasvisits: ", p), err)
		}
	}
	return err
}

func (p *User) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetAnnouncedActivities() {
		if err := oprot.WriteFieldBegin("announced_activities", thrift.LIST, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:announced_activities: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.AnnouncedActivities)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.AnnouncedActivities {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:announced_activities: ", p), err)
		}
	}
	return err
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

// Attributes:
//  - Lat
//  - Lon
type Coordinate struct {
	Lat float64 `thrift:"lat,1,required" db:"lat" json:"lat"`
	Lon float64 `thrift:"lon,2,required" db:"lon" json:"lon"`
}

func NewCoordinate() *Coordinate {
	return &Coordinate{}
}

func (p *Coordinate) GetLat() float64 {
	return p.Lat
}

func (p *Coordinate) GetLon() float64 {
	return p.Lon
}
func (p *Coordinate) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetLat bool = false
	var issetLon bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
			issetLat = true
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
			issetLon = true
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetLat {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Lat is not set"))
	}
	if !issetLon {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Lon is not set"))
	}
	return nil
}

func (p *Coordinate) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Lat = v
	}
	return nil
}

func (p *Coordinate) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Lon = v
	}
	return nil
}

func (p *Coordinate) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Coordinate"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Coordinate) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("lat", thrift.DOUBLE, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:lat: ", p), err)
	}
	if err := oprot.WriteDouble(float64(p.Lat)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.lat (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:lat: ", p), err)
	}
	return err
}

func (p *Coordinate) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("lon", thrift.DOUBLE, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:lon: ", p), err)
	}
	if err := oprot.WriteDouble(float64(p.Lon)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.lon (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:lon: ", p), err)
	}
	return err
}

func (p *Coordinate) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Coordinate(%+v)", *p)
}

// Attributes:
//  - ID
//  - Content
//  - Creator
//  - Bcontent
type Image struct {
	ID       *string `thrift:"id,1" db:"id" json:"id,omitempty"`
	Content  *string `thrift:"content,2" db:"content" json:"content,omitempty"`
	Creator  *string `thrift:"creator,3" db:"creator" json:"creator,omitempty"`
	Bcontent []byte  `thrift:"bcontent,4" db:"bcontent" json:"bcontent,omitempty"`
}

func NewImage() *Image {
	return &Image{}
}

var Image_ID_DEFAULT string

func (p *Image) GetID() string {
	if !p.IsSetID() {
		return Image_ID_DEFAULT
	}
	return *p.ID
}

var Image_Content_DEFAULT string

func (p *Image) GetContent() string {
	if !p.IsSetContent() {
		return Image_Content_DEFAULT
	}
	return *p.Content
}

var Image_Creator_DEFAULT string

func (p *Image) GetCreator() string {
	if !p.IsSetCreator() {
		return Image_Creator_DEFAULT
	}
	return *p.Creator
}

var Image_Bcontent_DEFAULT []byte

func (p *Image) GetBcontent() []byte {
	return p.Bcontent
}
func (p *Image) IsSetID() bool {
	return p.ID != nil
}

func (p *Image) IsSetContent() bool {
	return p.Content != nil
}

func (p *Image) IsSetCreator() bool {
	return p.Creator != nil
}

func (p *Image) IsSetBcontent() bool {
	return p.Bcontent != nil
}

func (p *Image) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Image) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = &v
	}
	return nil
}

func (p *Image) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Content = &v
	}
	return nil
}

func (p *Image) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Creator = &v
	}
	return nil
}

func (p *Image) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Bcontent = v
	}
	return nil
}

func (p *Image) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Image"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Image) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err := oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
		}
		if err := oprot.WriteString(string(*p.ID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
		}
	}
	return err
}

func (p *Image) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetContent() {
		if err := oprot.WriteFieldBegin("content", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:content: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Content)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.content (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:content: ", p), err)
		}
	}
	return err
}

func (p *Image) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreator() {
		if err := oprot.WriteFieldBegin("creator", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:creator: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Creator)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.creator (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:creator: ", p), err)
		}
	}
	return err
}

func (p *Image) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetBcontent() {
		if err := oprot.WriteFieldBegin("bcontent", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:bcontent: ", p), err)
		}
		if err := oprot.WriteBinary(p.Bcontent); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.bcontent (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:bcontent: ", p), err)
		}
	}
	return err
}

func (p *Image) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Image(%+v)", *p)
}

// Attributes:
//  - ID
//  - Name
//  - Icon
//  - Iconid
type Sport struct {
	ID     *string `thrift:"id,1" bson:"id,omitempty"`
	Name   *string `thrift:"name,2" bson:"name,omitempty"`
	Icon   *Image  `thrift:"icon,3" bson:"image,omitempty"`
	Iconid *string `thrift:"iconid,4" bson:"imageid,omitempty"`
}

func NewSport() *Sport {
	return &Sport{}
}

var Sport_ID_DEFAULT string

func (p *Sport) GetID() string {
	if !p.IsSetID() {
		return Sport_ID_DEFAULT
	}
	return *p.ID
}

var Sport_Name_DEFAULT string

func (p *Sport) GetName() string {
	if !p.IsSetName() {
		return Sport_Name_DEFAULT
	}
	return *p.Name
}

var Sport_Icon_DEFAULT *Image

func (p *Sport) GetIcon() *Image {
	if !p.IsSetIcon() {
		return Sport_Icon_DEFAULT
	}
	return p.Icon
}

var Sport_Iconid_DEFAULT string

func (p *Sport) GetIconid() string {
	if !p.IsSetIconid() {
		return Sport_Iconid_DEFAULT
	}
	return *p.Iconid
}
func (p *Sport) IsSetID() bool {
	return p.ID != nil
}

func (p *Sport) IsSetName() bool {
	return p.Name != nil
}

func (p *Sport) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *Sport) IsSetIconid() bool {
	return p.Iconid != nil
}

func (p *Sport) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Sport) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = &v
	}
	return nil
}

func (p *Sport) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Name = &v
	}
	return nil
}

func (p *Sport) ReadField3(iprot thrift.TProtocol) error {
	p.Icon = &Image{}
	if err := p.Icon.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Icon), err)
	}
	return nil
}

func (p *Sport) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Iconid = &v
	}
	return nil
}

func (p *Sport) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Sport"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Sport) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err := oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
		}
		if err := oprot.WriteString(string(*p.ID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
		}
	}
	return err
}

func (p *Sport) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetName() {
		if err := oprot.WriteFieldBegin("name", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:name: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Name)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.name (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:name: ", p), err)
		}
	}
	return err
}

func (p *Sport) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetIcon() {
		if err := oprot.WriteFieldBegin("icon", thrift.STRUCT, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:icon: ", p), err)
		}
		if err := p.Icon.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Icon), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:icon: ", p), err)
		}
	}
	return err
}

func (p *Sport) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetIconid() {
		if err := oprot.WriteFieldBegin("iconid", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:iconid: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Iconid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.iconid (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:iconid: ", p), err)
		}
	}
	return err
}

func (p *Sport) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Sport(%+v)", *p)
}

// Attributes:
//  - ID
//  - Title
//  - Sports
//  - Center
//  - Coords
//  - Description
//  - Cityid
//  - Imageid
type Area struct {
	ID          *string       `thrift:"id,1" bson:"areaid,omitempty"`
	Title       *string       `thrift:"title,2" bson:"title,omitempty"`
	Sports      []string      `thrift:"sports,3" bson:"sports,omitempty"`
	Center      []float64     `thrift:"center,4" bson:"center,omitempty"`
	Coords      []*Coordinate `thrift:"coords,5" bson:"coords,omitempty"`
	Description *string       `thrift:"description,6" bson:"description,omitempty"`
	Cityid      *string       `thrift:"cityid,7" bson:"cityid,omitempty"`
	Imageid     *string       `thrift:"imageid,8" bson:"iamgeid,omitempty"`
}

func NewArea() *Area {
	return &Area{}
}

var Area_ID_DEFAULT string

func (p *Area) GetID() string {
	if !p.IsSetID() {
		return Area_ID_DEFAULT
	}
	return *p.ID
}

var Area_Title_DEFAULT string

func (p *Area) GetTitle() string {
	if !p.IsSetTitle() {
		return Area_Title_DEFAULT
	}
	return *p.Title
}

var Area_Sports_DEFAULT []string

func (p *Area) GetSports() []string {
	return p.Sports
}

var Area_Center_DEFAULT []float64

func (p *Area) GetCenter() []float64 {
	return p.Center
}

var Area_Coords_DEFAULT []*Coordinate

func (p *Area) GetCoords() []*Coordinate {
	return p.Coords
}

var Area_Description_DEFAULT string

func (p *Area) GetDescription() string {
	if !p.IsSetDescription() {
		return Area_Description_DEFAULT
	}
	return *p.Description
}

var Area_Cityid_DEFAULT string

func (p *Area) GetCityid() string {
	if !p.IsSetCityid() {
		return Area_Cityid_DEFAULT
	}
	return *p.Cityid
}

var Area_Imageid_DEFAULT string

func (p *Area) GetImageid() string {
	if !p.IsSetImageid() {
		return Area_Imageid_DEFAULT
	}
	return *p.Imageid
}
func (p *Area) IsSetID() bool {
	return p.ID != nil
}

func (p *Area) IsSetTitle() bool {
	return p.Title != nil
}

func (p *Area) IsSetSports() bool {
	return p.Sports != nil
}

func (p *Area) IsSetCenter() bool {
	return p.Center != nil
}

func (p *Area) IsSetCoords() bool {
	return p.Coords != nil
}

func (p *Area) IsSetDescription() bool {
	return p.Description != nil
}

func (p *Area) IsSetCityid() bool {
	return p.Cityid != nil
}

func (p *Area) IsSetImageid() bool {
	return p.Imageid != nil
}

func (p *Area) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Area) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = &v
	}
	return nil
}

func (p *Area) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Title = &v
	}
	return nil
}

func (p *Area) ReadField3(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Sports = tSlice
	for i := 0; i < size; i++ {
		var _elem5 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem5 = v
		}
		p.Sports = append(p.Sports, _elem5)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *Area) ReadField4(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]float64, 0, size)
	p.Center = tSlice
	for i := 0; i < size; i++ {
		var _elem6 float64
		if v, err := iprot.ReadDouble(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem6 = v
		}
		p.Center = append(p.Center, _elem6)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *Area) ReadField5(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*Coordinate, 0, size)
	p.Coords = tSlice
	for i := 0; i < size; i++ {
		_elem7 := &Coordinate{}
		if err := _elem7.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem7), err)
		}
		p.Coords = append(p.Coords, _elem7)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *Area) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.Description = &v
	}
	return nil
}

func (p *Area) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.Cityid = &v
	}
	return nil
}

func (p *Area) ReadField8(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		p.Imageid = &v
	}
	return nil
}

func (p *Area) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Area"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Area) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err := oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
		}
		if err := oprot.WriteString(string(*p.ID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetTitle() {
		if err := oprot.WriteFieldBegin("title", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:title: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Title)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.title (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:title: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSports() {
		if err := oprot.WriteFieldBegin("sports", thrift.LIST, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:sports: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Sports)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Sports {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:sports: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCenter() {
		if err := oprot.WriteFieldBegin("center", thrift.LIST, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:center: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.DOUBLE, len(p.Center)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Center {
			if err := oprot.WriteDouble(float64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:center: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetCoords() {
		if err := oprot.WriteFieldBegin("coords", thrift.LIST, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:coords: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Coords)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Coords {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:coords: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetDescription() {
		if err := oprot.WriteFieldBegin("description", thrift.STRING, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:description: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Description)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.description (6) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:description: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetCityid() {
		if err := oprot.WriteFieldBegin("cityid", thrift.STRING, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:cityid: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Cityid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.cityid (7) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:cityid: ", p), err)
		}
	}
	return err
}

func (p *Area) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetImageid() {
		if err := oprot.WriteFieldBegin("imageid", thrift.STRING, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:imageid: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Imageid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.imageid (8) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:imageid: ", p), err)
		}
	}
	return err
}

func (p *Area) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Area(%+v)", *p)
}

// Attributes:
//  - ID
//  - Hostid
//  - Sport
//  - Area
//  - Cityid
//  - MaxParticipants
//  - Date
//  - Description
//  - Participants
//  - ParticipantsRequests
//  - ActPublic
type SportActivity struct {
	ID                   *string  `thrift:"id,1" bson:"activityid,omitempty"`
	Hostid               *string  `thrift:"hostid,2" bson:"hostid,omitempty"`
	Sport                *string  `thrift:"sport,3" bson:"sportid,omitempty"`
	Area                 *string  `thrift:"area,4" bson:"areaid,omitempty"`
	Cityid               *string  `thrift:"cityid,5" bson:"cityid,omitempty"`
	MaxParticipants      *int32   `thrift:"max_participants,6" bson:"max_participants,omitempty"`
	Date                 *int64   `thrift:"date,7" bson:"activity_date,omitempty"`
	Description          *string  `thrift:"description,8" bson:"description,omitempty"`
	Participants         []string `thrift:"participants,9" bson:"participants,omitempty"`
	ParticipantsRequests []string `thrift:"participants_requests,10" bson:"participants_requests,omitempty"`
	ActPublic            *bool    `thrift:"act_public,11" bson:"act_public,omitempty"`
}

func NewSportActivity() *SportActivity {
	return &SportActivity{}
}

var SportActivity_ID_DEFAULT string

func (p *SportActivity) GetID() string {
	if !p.IsSetID() {
		return SportActivity_ID_DEFAULT
	}
	return *p.ID
}

var SportActivity_Hostid_DEFAULT string

func (p *SportActivity) GetHostid() string {
	if !p.IsSetHostid() {
		return SportActivity_Hostid_DEFAULT
	}
	return *p.Hostid
}

var SportActivity_Sport_DEFAULT string

func (p *SportActivity) GetSport() string {
	if !p.IsSetSport() {
		return SportActivity_Sport_DEFAULT
	}
	return *p.Sport
}

var SportActivity_Area_DEFAULT string

func (p *SportActivity) GetArea() string {
	if !p.IsSetArea() {
		return SportActivity_Area_DEFAULT
	}
	return *p.Area
}

var SportActivity_Cityid_DEFAULT string

func (p *SportActivity) GetCityid() string {
	if !p.IsSetCityid() {
		return SportActivity_Cityid_DEFAULT
	}
	return *p.Cityid
}

var SportActivity_MaxParticipants_DEFAULT int32

func (p *SportActivity) GetMaxParticipants() int32 {
	if !p.IsSetMaxParticipants() {
		return SportActivity_MaxParticipants_DEFAULT
	}
	return *p.MaxParticipants
}

var SportActivity_Date_DEFAULT int64

func (p *SportActivity) GetDate() int64 {
	if !p.IsSetDate() {
		return SportActivity_Date_DEFAULT
	}
	return *p.Date
}

var SportActivity_Description_DEFAULT string

func (p *SportActivity) GetDescription() string {
	if !p.IsSetDescription() {
		return SportActivity_Description_DEFAULT
	}
	return *p.Description
}

var SportActivity_Participants_DEFAULT []string

func (p *SportActivity) GetParticipants() []string {
	return p.Participants
}

var SportActivity_ParticipantsRequests_DEFAULT []string

func (p *SportActivity) GetParticipantsRequests() []string {
	return p.ParticipantsRequests
}

var SportActivity_ActPublic_DEFAULT bool

func (p *SportActivity) GetActPublic() bool {
	if !p.IsSetActPublic() {
		return SportActivity_ActPublic_DEFAULT
	}
	return *p.ActPublic
}
func (p *SportActivity) IsSetID() bool {
	return p.ID != nil
}

func (p *SportActivity) IsSetHostid() bool {
	return p.Hostid != nil
}

func (p *SportActivity) IsSetSport() bool {
	return p.Sport != nil
}

func (p *SportActivity) IsSetArea() bool {
	return p.Area != nil
}

func (p *SportActivity) IsSetCityid() bool {
	return p.Cityid != nil
}

func (p *SportActivity) IsSetMaxParticipants() bool {
	return p.MaxParticipants != nil
}

func (p *SportActivity) IsSetDate() bool {
	return p.Date != nil
}

func (p *SportActivity) IsSetDescription() bool {
	return p.Description != nil
}

func (p *SportActivity) IsSetParticipants() bool {
	return p.Participants != nil
}

func (p *SportActivity) IsSetParticipantsRequests() bool {
	return p.ParticipantsRequests != nil
}

func (p *SportActivity) IsSetActPublic() bool {
	return p.ActPublic != nil
}

func (p *SportActivity) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		case 9:
			if err := p.ReadField9(iprot); err != nil {
				return err
			}
		case 10:
			if err := p.ReadField10(iprot); err != nil {
				return err
			}
		case 11:
			if err := p.ReadField11(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *SportActivity) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = &v
	}
	return nil
}

func (p *SportActivity) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Hostid = &v
	}
	return nil
}

func (p *SportActivity) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Sport = &v
	}
	return nil
}

func (p *SportActivity) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Area = &v
	}
	return nil
}

func (p *SportActivity) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.Cityid = &v
	}
	return nil
}

func (p *SportActivity) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.MaxParticipants = &v
	}
	return nil
}

func (p *SportActivity) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.Date = &v
	}
	return nil
}

func (p *SportActivity) ReadField8(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		p.Description = &v
	}
	return nil
}

func (p *SportActivity) ReadField9(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Participants = tSlice
	for i := 0; i < size; i++ {
		var _elem8 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem8 = v
		}
		p.Participants = append(p.Participants, _elem8)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *SportActivity) ReadField10(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.ParticipantsRequests = tSlice
	for i := 0; i < size; i++ {
		var _elem9 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem9 = v
		}
		p.ParticipantsRequests = append(p.ParticipantsRequests, _elem9)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *SportActivity) ReadField11(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return thrift.PrependError("error reading field 11: ", err)
	} else {
		p.ActPublic = &v
	}
	return nil
}

func (p *SportActivity) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SportActivity"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := p.writeField9(oprot); err != nil {
		return err
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField11(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *SportActivity) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err := oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
		}
		if err := oprot.WriteString(string(*p.ID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetHostid() {
		if err := oprot.WriteFieldBegin("hostid", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:hostid: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Hostid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.hostid (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:hostid: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSport() {
		if err := oprot.WriteFieldBegin("sport", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:sport: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Sport)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.sport (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:sport: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetArea() {
		if err := oprot.WriteFieldBegin("area", thrift.STRING, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:area: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Area)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.area (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:area: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetCityid() {
		if err := oprot.WriteFieldBegin("cityid", thrift.STRING, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:cityid: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Cityid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.cityid (5) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:cityid: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetMaxParticipants() {
		if err := oprot.WriteFieldBegin("max_participants", thrift.I32, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:max_participants: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.MaxParticipants)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.max_participants (6) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:max_participants: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetDate() {
		if err := oprot.WriteFieldBegin("date", thrift.I64, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:date: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.Date)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.date (7) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:date: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetDescription() {
		if err := oprot.WriteFieldBegin("description", thrift.STRING, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:description: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Description)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.description (8) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:description: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetParticipants() {
		if err := oprot.WriteFieldBegin("participants", thrift.LIST, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:participants: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Participants)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Participants {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:participants: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetParticipantsRequests() {
		if err := oprot.WriteFieldBegin("participants_requests", thrift.LIST, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:participants_requests: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.ParticipantsRequests)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.ParticipantsRequests {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:participants_requests: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetActPublic() {
		if err := oprot.WriteFieldBegin("act_public", thrift.BOOL, 11); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 11:act_public: ", p), err)
		}
		if err := oprot.WriteBool(bool(*p.ActPublic)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.act_public (11) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 11:act_public: ", p), err)
		}
	}
	return err
}

func (p *SportActivity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SportActivity(%+v)", *p)
}

// Attributes:
//  - ID
//  - Name
//  - Coords
//  - Center
//  - Sportactivities
type City struct {
	ID              string        `thrift:"id,1,required" bson:"cityid,omitempty"`
	Name            string        `thrift:"name,2,required" bson:"name,omitempty"`
	Coords          []*Coordinate `thrift:"coords,3" bson:"coords,omitempty"`
	Center          *Coordinate   `thrift:"center,4" bson:"center,omitempty"`
	Sportactivities []string      `thrift:"sportactivities,5" bson:"sportactivities,omitempty"`
}

func NewCity() *City {
	return &City{}
}

func (p *City) GetID() string {
	return p.ID
}

func (p *City) GetName() string {
	return p.Name
}

var City_Coords_DEFAULT []*Coordinate

func (p *City) GetCoords() []*Coordinate {
	return p.Coords
}

var City_Center_DEFAULT *Coordinate

func (p *City) GetCenter() *Coordinate {
	if !p.IsSetCenter() {
		return City_Center_DEFAULT
	}
	return p.Center
}

var City_Sportactivities_DEFAULT []string

func (p *City) GetSportactivities() []string {
	return p.Sportactivities
}
func (p *City) IsSetCoords() bool {
	return p.Coords != nil
}

func (p *City) IsSetCenter() bool {
	return p.Center != nil
}

func (p *City) IsSetSportactivities() bool {
	return p.Sportactivities != nil
}

func (p *City) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetID bool = false
	var issetName bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
			issetID = true
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
			issetName = true
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetID {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ID is not set"))
	}
	if !issetName {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Name is not set"))
	}
	return nil
}

func (p *City) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = v
	}
	return nil
}

func (p *City) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *City) ReadField3(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*Coordinate, 0, size)
	p.Coords = tSlice
	for i := 0; i < size; i++ {
		_elem10 := &Coordinate{}
		if err := _elem10.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem10), err)
		}
		p.Coords = append(p.Coords, _elem10)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *City) ReadField4(iprot thrift.TProtocol) error {
	p.Center = &Coordinate{}
	if err := p.Center.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Center), err)
	}
	return nil
}

func (p *City) ReadField5(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Sportactivities = tSlice
	for i := 0; i < size; i++ {
		var _elem11 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem11 = v
		}
		p.Sportactivities = append(p.Sportactivities, _elem11)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *City) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("City"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *City) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
	}
	if err := oprot.WriteString(string(p.ID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
	}
	return err
}

func (p *City) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("name", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:name: ", p), err)
	}
	if err := oprot.WriteString(string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:name: ", p), err)
	}
	return err
}

func (p *City) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetCoords() {
		if err := oprot.WriteFieldBegin("coords", thrift.LIST, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:coords: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Coords)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Coords {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:coords: ", p), err)
		}
	}
	return err
}

func (p *City) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCenter() {
		if err := oprot.WriteFieldBegin("center", thrift.STRUCT, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:center: ", p), err)
		}
		if err := p.Center.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Center), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:center: ", p), err)
		}
	}
	return err
}

func (p *City) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetSportactivities() {
		if err := oprot.WriteFieldBegin("sportactivities", thrift.LIST, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:sportactivities: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Sportactivities)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Sportactivities {
			if err := oprot.WriteString(string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:sportactivities: ", p), err)
		}
	}
	return err
}

func (p *City) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("City(%+v)", *p)
}
